### ISSUE TITLE
Design Database

### ISSUE THREAD

**Issue by webkaruna198** [pnc-virtual-company/2020-G8-LMS#3]

**Comment by kimhuy734** [comment]
@radytrainer 
Good afternoon Manager.
Could you check our database design?
Thank you.
best regards,
kimhuy soth

**Comment by kimhuy734** [comment]
@radytrainer 
Good afternoon Manager.
Now we already updated our database design. So please you check ours again.
Thank you so much.
Best Regards,
kimhuy soth

**Comment by kimhuy734** [comment]
@radytrainer 
Good evening Manager.
Now we already updated our database design. So please you check ours again.
Thank you so much.
Best Regards,
kimhuy soth
