### ISSUE TITLE
Your Leaves: controller/Model/Create

### ISSUE THREAD

**Issue by kimhuy734** [pnc-virtual-company/2020-G8-LMS#51]
-user can create leave request
-If user don't filter information so they can't create leave request and it will alert message error
-  If user filter correct information so they can create leave request
- Start date and end date cannot be selected in the past
- End date cannot be before start date
- A leave duration is automatically calculated by the system, based on start date and
end date
- When clicking on SUBMIT button, the request is sent to the MANAGER and its status is REQUESTED
- On button search user can search all information on table.

**Comment by Hy-Hong99** [comment]
@radytrainer 
Hello teacher, please checks our leave request
