### ISSUE TITLE
Your Leaves: controller/Model/Delete

### ISSUE THREAD

**Issue by sophoanteng** [pnc-virtual-company/2020-G8-LMS#62]
-HR OFFICER or ADMIN can delete leaves request
-When HR OFFICER or ADMIN click on icon delete it will alert message tell to user want to delete or not.
-If HR OFFICER or ADMIN click on delete it will delete information on table.
-If HR OFFICER or ADMIN click on cancel so all information don't delete.
-Only HR OFFICER or ADMIN can delete any employees leave requests

**Comment by kimhuy734** [comment]
@radytrainer 

Dear Manager,

I would like to invite you to check my task of Delete Your Leaves.

Best Regards,

kimhuy soth
